// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0JGWndrldHL6kGhUchpisUle_7w_oqnk',
    appId: '1:768064139489:web:390359f57344a64c04c7a0',
    messagingSenderId: '768064139489',
    projectId: 'kc-attendance-app',
    authDomain: 'kc-attendance-app.firebaseapp.com',
    storageBucket: 'kc-attendance-app.firebasestorage.app',
    measurementId: 'G-28LY9WL4J2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAooT3tXlCg6c93_ryFcYcGn3g8eEBj_cs',
    appId: '1:768064139489:android:3293a1939a57794604c7a0',
    messagingSenderId: '768064139489',
    projectId: 'kc-attendance-app',
    storageBucket: 'kc-attendance-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA96SD0iMRBv5-5cPLFskgfRG1T4jhFHUU',
    appId: '1:768064139489:ios:5d5df4bca971b4b804c7a0',
    messagingSenderId: '768064139489',
    projectId: 'kc-attendance-app',
    storageBucket: 'kc-attendance-app.firebasestorage.app',
    iosBundleId: 'com.example.pictMis',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD0JGWndrldHL6kGhUchpisUle_7w_oqnk',
    appId: '1:768064139489:web:0e0fb9de2612198004c7a0',
    messagingSenderId: '768064139489',
    projectId: 'kc-attendance-app',
    authDomain: 'kc-attendance-app.firebaseapp.com',
    storageBucket: 'kc-attendance-app.firebasestorage.app',
    measurementId: 'G-FL5P7KNX45',
  );
}
